// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnsmtrnhiediwqvedbpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Induc210cm5oaWVkaXdxdmVkYnBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MDQ1ODYsImV4cCI6MjA2NjA4MDU4Nn0.1VGEBF82OlcPEm0OXDCAk0Wl7Iwju05wbAG-cWqrezQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});